services:
  - type: web
    name: mts-purchase-service
    runtime: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /v3/api-docs
    envVars:
      - key: PROJ_ENVIRONMENT
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
