spring.application.name=mts-purchase-service
# ─────────────────────────────────────────────────────────────
# application.properties
# ─────────────────────────────────────────────────────────────

# ── Active Profile ────────────────────────────────────────────
spring.profiles.active=${PROJ_ENVIRONMENT}



# ── Server ────────────────────────────────────────────────────
server.address=0.0.0.0
server.port=8080

# ── JPA / Hibernate ───────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate

# Print SQL queries to console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Oracle dialect — tells Hibernate to generate Oracle-compatible SQL
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Prevent "open session in view" warning
spring.jpa.open-in-view=false

# ── Connection Pool (HikariCP — Spring Boot default) ──────────
# HikariCP is bundled with spring-boot-starter-data-jpa
# Tune these based on your machine's available resources
spring.datasource.hikari.pool-name=mtspurchaseservicepool
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-init-sql=ALTER SESSION DISABLE PARALLEL DML


# ── Logging ───────────────────────────────────────────────────
# Your app code
logging.level.com.mts.mts_purchase_service=INFO
# Show Hibernate SQL bindings (shows actual values in queries)
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=WARN
# Suppress noisy Spring startup logs
logging.level.org.springframework=WARN
logging.level.org.springframework.web=INFO
# Log file location
logging.file.name=logs/mts.log
