# ─────────────────────────────────────────────────────────────
# application-prod.properties
# ─────────────────────────────────────────────────────────────

# ── Oracle DataSource ─────────────────────────────────────────
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Connection URL format:
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-mumbai-1.oraclecloud.com))(connect_data=(service_name=g9c5b20ed51a0b3_mtsuatdb_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Show formatted SQL in console during development
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Use 'update' in early development so Hibernate adjusts tables
# automatically when you add/change entity fields.
# Switch back to 'validate' once schema is stable.
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.com.mts.mts_purchase_service=INFO

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://mtsfinance.in,https://www.mtsfinance.in}

# Security: require HTTPS transport for auth endpoints in UAT.
auth.transport.require-https=true
