-- Creates application user credential table for secure login.
CREATE TABLE app_users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(100 CHAR) NOT NULL,
    password_hash  VARCHAR2(255 CHAR) NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at     TIMESTAMP
);

ALTER TABLE app_users
    ADD CONSTRAINT uk_app_users_username UNIQUE (username);
