-- Stores pending OTP-backed new-user registration requests.
CREATE TABLE user_registration_otps (
    otp_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(100 CHAR) NOT NULL,
    password_hash  VARCHAR2(255 CHAR) NOT NULL,
    otp_hash       VARCHAR2(64 CHAR) NOT NULL,
    owner_email    VARCHAR2(150 CHAR) NOT NULL,
    expires_at     TIMESTAMP NOT NULL,
    attempts_left  NUMBER(2) DEFAULT 5 NOT NULL,
    is_verified    NUMBER(1) DEFAULT 0 NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    consumed_at    TIMESTAMP
);

CREATE INDEX idx_reg_otp_user_active ON user_registration_otps (LOWER(username), is_verified, consumed_at);
CREATE INDEX idx_reg_otp_expiry ON user_registration_otps (expires_at);
